/**
 * MSLS Merit List & Admission Decision Models
 *
 * Defines interfaces for merit list generation, admission decisions,
 * and enrollment processes.
 */

/**
 * Application status types
 */
export type ApplicationStatus =
  | 'submitted'
  | 'under_review'
  | 'test_scheduled'
  | 'test_completed'
  | 'selected'
  | 'waitlisted'
  | 'rejected'
  | 'offer_sent'
  | 'offer_accepted'
  | 'enrolled'
  | 'withdrawn';

/**
 * Decision types for admission
 */
export type DecisionType = 'selected' | 'waitlisted' | 'rejected';

/**
 * Merit list entry for a single applicant
 */
export interface MeritListEntry {
  /** Unique identifier */
  id: string;

  /** Application ID */
  applicationId: string;

  /** Applicant's name */
  studentName: string;

  /** Parent/guardian name */
  parentName: string;

  /** Parent phone */
  parentPhone: string;

  /** Parent email */
  parentEmail?: string;

  /** Application number */
  applicationNumber: string;

  /** Class applied for */
  classApplying: string;

  /** Total test score */
  totalScore: number;

  /** Maximum possible score */
  maxScore: number;

  /** Percentage score */
  percentage: number;

  /** Rank in merit list */
  rank: number;

  /** Current application status */
  status: ApplicationStatus;

  /** Test ID if applicable */
  testId?: string;

  /** Test name */
  testName?: string;

  /** Individual subject scores */
  subjectScores?: SubjectScore[];

  /** Section assigned if selected */
  sectionAssigned?: string;

  /** Waitlist position if waitlisted */
  waitlistPosition?: number;

  /** Decision date */
  decisionDate?: string;

  /** Decided by user ID */
  decidedBy?: string;

  /** Decision remarks */
  remarks?: string;
}

/**
 * Subject-wise score breakdown
 */
export interface SubjectScore {
  subjectName: string;
  score: number;
  maxScore: number;
}

/**
 * Merit list response from API
 */
export interface MeritList {
  /** Unique identifier */
  id: string;

  /** Tenant ID */
  tenantId: string;

  /** Session ID */
  sessionId: string;

  /** Class name this merit list is for */
  className: string;

  /** Test ID if based on entrance test */
  testId?: string;

  /** Test name */
  testName?: string;

  /** When the merit list was generated */
  generatedAt: string;

  /** Generated by user ID */
  generatedBy?: string;

  /** Cutoff score applied */
  cutoffScore?: number;

  /** Merit list entries */
  entries: MeritListEntry[];

  /** Whether this is the final/published list */
  isFinal: boolean;

  /** Created timestamp */
  createdAt: string;
}

/**
 * Admission decision record
 */
export interface AdmissionDecision {
  /** Unique identifier */
  id: string;

  /** Tenant ID */
  tenantId: string;

  /** Application ID */
  applicationId: string;

  /** Decision type */
  decision: DecisionType;

  /** Date of decision */
  decisionDate: string;

  /** User who made the decision */
  decidedBy?: string;

  /** Section assigned (for selected students) */
  sectionAssigned?: string;

  /** Waitlist position (for waitlisted students) */
  waitlistPosition?: number;

  /** Rejection reason (for rejected students) */
  rejectionReason?: string;

  /** URL to generated offer letter */
  offerLetterUrl?: string;

  /** Offer validity date */
  offerValidUntil?: string;

  /** Whether offer was accepted */
  offerAccepted?: boolean;

  /** When offer was accepted */
  offerAcceptedAt?: string;

  /** Additional remarks */
  remarks?: string;

  /** Created timestamp */
  createdAt: string;

  /** Updated timestamp */
  updatedAt: string;
}

/**
 * Request to generate merit list
 */
export interface GenerateMeritListRequest {
  className: string;
  testId?: string;
  cutoffScore?: number;
}

/**
 * Request to make admission decision
 */
export interface MakeDecisionRequest {
  decision: DecisionType;
  sectionAssigned?: string;
  waitlistPosition?: number;
  rejectionReason?: string;
  remarks?: string;
  offerValidUntil?: string;
}

/**
 * Bulk decision request for multiple applications
 */
export interface BulkDecisionRequest {
  applicationIds: string[];
  decision: DecisionType;
  sectionAssigned?: string;
  remarks?: string;
  offerValidUntil?: string;
}

/**
 * Bulk decision response from API
 */
export interface BulkDecisionResponse {
  successful: number;
  failed: number;
  decisions: AdmissionDecision[];
  errors?: BulkDecisionError[];
}

/**
 * Error in bulk decision processing
 */
export interface BulkDecisionError {
  applicationId: string;
  error: string;
}

/**
 * Request to accept an offer
 */
export interface AcceptOfferRequest {
  paymentMethod?: string;
  paymentReference?: string;
  remarks?: string;
}

/**
 * Enrollment request
 */
export interface EnrollmentRequest {
  sectionId?: string;
  rollNumber?: string;
  admissionDate?: string;
  remarks?: string;
}

/**
 * Enrollment response
 */
export interface EnrollmentResponse {
  applicationId: string;
  studentId?: string;
  enrollmentNumber?: string;
  admissionDate: string;
  className: string;
  sectionName?: string;
  rollNumber?: string;
}

/**
 * Status configuration for display
 */
export interface StatusConfig {
  label: string;
  variant: 'primary' | 'success' | 'warning' | 'danger' | 'info' | 'neutral';
  icon: string;
}

/**
 * Application status display configuration
 */
export const APPLICATION_STATUS_CONFIG: Record<ApplicationStatus, StatusConfig> = {
  submitted: {
    label: 'Submitted',
    variant: 'info',
    icon: 'fa-solid fa-paper-plane',
  },
  under_review: {
    label: 'Under Review',
    variant: 'primary',
    icon: 'fa-solid fa-magnifying-glass',
  },
  test_scheduled: {
    label: 'Test Scheduled',
    variant: 'info',
    icon: 'fa-solid fa-calendar',
  },
  test_completed: {
    label: 'Test Completed',
    variant: 'primary',
    icon: 'fa-solid fa-check',
  },
  selected: {
    label: 'Selected',
    variant: 'success',
    icon: 'fa-solid fa-circle-check',
  },
  waitlisted: {
    label: 'Waitlisted',
    variant: 'warning',
    icon: 'fa-solid fa-clock',
  },
  rejected: {
    label: 'Rejected',
    variant: 'danger',
    icon: 'fa-solid fa-circle-xmark',
  },
  offer_sent: {
    label: 'Offer Sent',
    variant: 'success',
    icon: 'fa-solid fa-envelope',
  },
  offer_accepted: {
    label: 'Offer Accepted',
    variant: 'success',
    icon: 'fa-solid fa-handshake',
  },
  enrolled: {
    label: 'Enrolled',
    variant: 'success',
    icon: 'fa-solid fa-user-graduate',
  },
  withdrawn: {
    label: 'Withdrawn',
    variant: 'neutral',
    icon: 'fa-solid fa-ban',
  },
};

/**
 * Decision type display configuration
 */
export const DECISION_TYPE_CONFIG: Record<DecisionType, StatusConfig> = {
  selected: {
    label: 'Selected',
    variant: 'success',
    icon: 'fa-solid fa-circle-check',
  },
  waitlisted: {
    label: 'Waitlisted',
    variant: 'warning',
    icon: 'fa-solid fa-clock',
  },
  rejected: {
    label: 'Rejected',
    variant: 'danger',
    icon: 'fa-solid fa-circle-xmark',
  },
};

/**
 * Get status display configuration
 */
export function getStatusConfig(status: ApplicationStatus): StatusConfig {
  return APPLICATION_STATUS_CONFIG[status] || {
    label: status,
    variant: 'neutral' as const,
    icon: 'fa-solid fa-circle',
  };
}

/**
 * Get decision type display configuration
 */
export function getDecisionConfig(decision: DecisionType): StatusConfig {
  return DECISION_TYPE_CONFIG[decision];
}
